version: '3.8'
services:
  dev-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: vukhac
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: plus-ultra
  data-warehouse:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: vukhac
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: data-warehouse
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass 123
    volumes:
      - ./redis/data:/data
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - rabbitmq.env
volumes:
  dev-db:
    driver: local
  cache:
    driver: local
